# Generated by Django 4.2.19 on 2025-02-23 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_genre_alter_movie_title_movie_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='movies', to='movies.genre'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='thumbnail',
            field=models.URLField(max_length=500),
        ),
    ]
