# Generated by Django 4.2.19 on 2025-02-23 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_movie_genres_alter_movie_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='patreon_title',
            field=models.CharField(default=models.CharField(max_length=200, unique=True), max_length=200),
        ),
    ]
