# Generated by Django 4.2.19 on 2025-02-23 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movie_patreon_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='type',
            field=models.CharField(choices=[('movie', 'Movie'), ('series', 'Series')], default='movie', max_length=10),
        ),
        migrations.AlterField(
            model_name='movie',
            name='patreon_title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
