# Generated by Django 4.2.19 on 2025-03-04 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_movie_type_alter_movie_patreon_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='movie',
            name='patreon_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
