# Generated by Django 4.2.19 on 2025-03-05 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_alter_movie_options_movie_release_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='release_year',
        ),
        migrations.AddField(
            model_name='movie',
            name='release_year_range',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
